import { Jost } from "next/font/google"
import "./globals.css"
import AuthProvider from "@/components/Utils/AuthProvider"
import { SWRProvider } from "@/components/Utils/SWRProvider"

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
    icons: {
        icon: "/favicon-32x32.png",
    },
}

const jost = Jost({
    subsets: ["latin"],
    variable: "--font-jost",
    display: "swap",
})

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" className={`${jost.variable}`}>
            <body>
                <AuthProvider>
                    <SWRProvider>{children}</SWRProvider>
                </AuthProvider>
            </body>
        </html>
    )
}
